# Generated by Django 5.2.7 on 2026-03-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('chapter', 'number', 'source_file')},
        ),
    ]
