# Generated by Django 5.2.7 on 2026-03-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_alter_verse_unique_together'),
    ]

    operations = [
        # Explicitly create pgvector extension BEFORE the VectorField gets applied
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            "DROP EXTENSION IF EXISTS vector;"
        ),
    ]
