# Generated by Django 5.2.7 on 2026-03-02 11:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_create_vector_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='embedding',
        ),
        migrations.AddField(
            model_name='verse',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
