# Generated by Django 5.2.7 on 2026-03-02 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0004_alter_verse_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AelfDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_endpoint', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('zone', models.CharField(db_index=True, max_length=50)),
                ('raw_json', models.JSONField(help_text='The exact JSON response returned by the API')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'AELF Data Entries',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='LiturgicalDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone', models.CharField(max_length=50)),
                ('day_name', models.CharField(blank=True, max_length=255)),
                ('season', models.CharField(blank=True, max_length=255)),
                ('mystery', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='AelfResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('liturgical_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='liturgy.liturgicaldate')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(max_length=50)),
                ('hymn', models.TextField(blank=True, help_text='Hymn text')),
                ('psalms', models.JSONField(blank=True, default=list, help_text='List of psalms/canticles objects')),
                ('canticle', models.TextField(blank=True, help_text='Main canticle (Benedictus/Magnificat/Nunc Dimittis)')),
                ('readings', models.JSONField(blank=True, default=list, help_text='Short readings and responsories')),
                ('intercessions', models.TextField(blank=True, help_text='Intercessions text')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Any additional unmodified data')),
                ('liturgical_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='liturgy.liturgicaldate')),
            ],
            options={
                'unique_together': {('liturgical_date', 'office_type')},
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('citation', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('liturgical_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='liturgy.liturgicaldate')),
                ('matched_verses', models.ManyToManyField(blank=True, help_text='Bible verses from our local DB matched to this reading citation.', related_name='liturgy_readings', to='bible.verse')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('liturgical_date', 'type', 'citation')},
            },
        ),
    ]
