# Generated by Django 5.2.7 on 2026-03-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedslot',
            options={'verbose_name': 'Créneau Bloqué', 'verbose_name_plural': 'Créneaux Bloqués'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='minister',
            options={'verbose_name': 'Ministre', 'verbose_name_plural': 'Ministres'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name': 'Paroisse', 'verbose_name_plural': 'Paroisses'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Type de Service', 'verbose_name_plural': 'Types de Service'},
        ),
        migrations.AlterModelOptions(
            name='specialavailability',
            options={'verbose_name': 'Disponibilité Spéciale', 'verbose_name_plural': 'Disponibilités Spéciales'},
        ),
        migrations.AlterModelOptions(
            name='weeklyavailability',
            options={'verbose_name': 'Disponibilité Hebdomadaire', 'verbose_name_plural': 'Disponibilités Hebdomadaires'},
        ),
    ]
