# Generated by Django 5.2.7 on 2026-03-13 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('youtube_url', models.URLField()),
                ('is_live', models.BooleanField(default=False)),
                ('is_pinned_live', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='tv.category')),
            ],
            options={
                'ordering': ['-is_pinned_live', '-is_live', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='tv_video_categor_0142f8_idx'), models.Index(fields=['is_live'], name='tv_video_is_live_b6099f_idx'), models.Index(fields=['is_pinned_live'], name='tv_video_is_pinn_43762c_idx')],
            },
        ),
    ]
