# Generated by Django 5.2.7 on 2026-03-01 15:32

import apps.rosary.storage
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, storage=apps.rosary.storage.RosaryAudioStorage(), upload_to='')),
                ('audio_duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysteries', to='rosary.mysterygroup')),
            ],
            options={
                'verbose_name_plural': 'Mysteries',
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SIGN_OF_CROSS', 'Sign of Cross'), ('CREED', 'Apostles Creed'), ('OUR_FATHER', 'Our Father'), ('HAIL_MARY', 'Hail Mary'), ('GLORY_BE', 'Glory Be'), ('FATIMA', 'Fatima Prayer'), ('HOLY_QUEEN', 'Hail Holy Queen'), ('FINAL_PRAYER', 'Final Prayer')], max_length=50)),
                ('text', models.TextField()),
                ('language', models.CharField(default='FR', max_length=10)),
                ('tsv', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='rosary_pray_type_e64e99_idx')],
            },
        ),
        migrations.CreateModel(
            name='MysteryPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('mystery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='rosary.mystery')),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysteries', to='rosary.prayer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RosaryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='rosary.mysterygroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='mystery',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='unique_mystery_order_per_group'),
        ),
        migrations.AddConstraint(
            model_name='mysteryprayer',
            constraint=models.UniqueConstraint(fields=('mystery', 'order'), name='unique_prayer_order_per_mystery'),
        ),
    ]
