# Generated by Django 5.2.7 on 2026-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='type',
            field=models.CharField(choices=[('SIGN_OF_CROSS', 'Sign of Cross'), ('CREED', 'Apostles Creed'), ('OUR_FATHER', 'Our Father'), ('HAIL_MARY', 'Hail Mary'), ('GLORY_BE', 'Glory Be'), ('FATIMA', 'Fatima Prayer'), ('HOLY_QUEEN', 'Hail Holy Queen'), ('FINAL_PRAYER', 'Final Prayer'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
