# Generated by Django 5.2.7 on 2026-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0002_alter_prayer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery',
            name='meditation',
            field=models.TextField(blank=True, help_text='Scripture reading or meditation for the mystery', null=True),
        ),
    ]
