# Generated by Django 5.2.7 on 2026-03-02 18:01

import apps.rosary.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0003_mystery_meditation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysterygroup',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=apps.rosary.storage.RosaryAudioStorage(), upload_to=''),
        ),
    ]
